#mariadb default username：root  password：123456
version: '3.8'
services:
  mariadb:
    container_name: mariadb10.2
    image: mariadb:10.2
    environment:
     - MYSQL_ROOT_PASSWORD=123456
    ports:
     - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
     - "./volumes/mysql_data:/var/lib/mysql"

networks:
  default:
      name: "apps"
