version: '3.1'

services:

  mariadb:
  
    container_name: mariadb_latest
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes: 
        - ./mysql_config:/etc/mysql
        - ./mysql_data:/var/lib/mysql
        
networks:
  default:
    external:
      name: "apps"
