# %%MARIADB_VERSION%% will be set by update.sh according to generating mariadb version image.
FROM mariadb:%%MARIADB_VERSION%%

RUN apt-get update && \
        apt-get install -y mariadb-plugin-columnstore=$MARIADB_VERSION ; \
        rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint-cs.sh /usr/local/bin/

ENTRYPOINT ["docker-entrypoint-cs.sh"]